#!/bin/sh
#*****************************************************************************
#* 
#*  @file          /etc/init.d/S12ccm2200_serial_init
#*
#*                 Create links in /dev with same name as SM2010 ports
#*                 and configure board specific CCM2200 serial modes
#*                 Buildroot uclibc linux
#*                 2006 Weiss-Electronic GmbH
#*
#*  @version       0.2
#*  @date          <2005-05-18 17:03:03 gc>
#*  @author        Guido Classen
#* 
#*  @par change history:
#*    2007-05-08 gc: adoption new LED concept!
#*    2006-12-07 gc: initial version 
#*  
#*****************************************************************************

case "$1" in
  start)
	# break
	;;
  stop)
  	exit 0
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

echo initializing serial ports

if test -c /dev/ttyAT0 
then

# new Kernel using /dev/ttyAT0 device name scheme for ATMEL Uarts
# ---------------- Atmel AT91RM9200 interne UARTs -------------------------

# COM2 Piggyback u.r.
ln -s /dev/ttyAT0 /dev/com2
# COM1 Piggyback o.r.
ln -s /dev/ttyAT1 /dev/com1
ln -s /dev/ttyAT2 /dev/ttySconsole
ln -s /dev/ttyAT2 /dev/com5
# COM6 Piggyback u.l.
ln -s /dev/ttyAT3 /dev/com6
ln -s /dev/ttyAT4 /dev/ttySdebug

# ---------------- externer QUAD-UART --------------------------------------
# COM3 RS485
ln -s /dev/ttyS0 /dev/com3
# COM4 Piggyback o.l.
ln -s /dev/ttyS1 /dev/com4
# Pfostenstecker oben
ln -s /dev/ttyS2 /dev/com7
# Pfostenstecker Mitte
ln -s /dev/ttyS3 /dev/com8



else
# ---------------- Atmel AT91RM9200 interne UARTs -------------------------



# COM2 Piggyback u.r.
ln -s /dev/ttyS0 /dev/com2
# COM1 Piggyback o.r.
ln -s /dev/ttyS1 /dev/com1
ln -s /dev/ttyS2 /dev/ttySconsole
ln -s /dev/ttyS2 /dev/com5
# COM6 Piggyback u.l.
ln -s /dev/ttyS3 /dev/com6
ln -s /dev/ttyS4 /dev/ttySdebug

# ---------------- externer QUAD-UART --------------------------------------
# COM3 RS485
ln -s /dev/ttyS5 /dev/com3
# COM4 Piggyback o.l.
ln -s /dev/ttyS6 /dev/com4
# Pfostenstecker oben
ln -s /dev/ttyS7 /dev/com7
# Pfostenstecker Mitte
ln -s /dev/ttyS8 /dev/com8

fi


# ---------------- assign RX / TX indicator LEDs ---------------------------
# com3 is always rs485kern!
ccm2200_serial /dev/com3 mode rs485kern 0 0
#ccm2200_serial /dev/com3 rxled $((1<<4)) 4
#ccm2200_serial /dev/com3 txled $((1<<5)) 4






