#!/bin/sh
#*****************************************************************************
#* 
#*  @file          /etc/S12sm2010device_nodes
#*
#*                 Create /dev entries with same name as SM2010 ports
#*                 Buildroot uclibc linux
#*                 2006 Weiss-Electronic GmbH
#*
#*  @version       0.2
#*  @date          <2005-05-18 17:03:03 gc>
#*  @author        Guido Classen
#* 
#*  @par change history:
#*    2006-12-07 gc: initial version 
#*  
#*****************************************************************************

case "$1" in
  start)
	# break
	;;
  stop)
  	exit 0
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

# ---------------- Atmel AT91RM9200 interne UARTs -------------------------

# COM2 Piggyback u.r.
ln -s /dev/ttyS0 /dev/com2
# COM1 Piggyback o.r.
ln -s /dev/ttyS1 /dev/com1
ln -s /dev/ttyS2 /dev/ttySconsole
ln -s /dev/ttyS2 /dev/com5
# COM6 Piggyback u.l.
ln -s /dev/ttyS3 /dev/com6
ln -s /dev/ttyS4 /dev/ttySdebug

# ---------------- externer QUAD-UART --------------------------------------
# COM3 RS485
ln -s /dev/ttySU0 /dev/com3
# COM4 Piggyback o.l.
ln -s /dev/ttySU1 /dev/com4
# Pfostenstecker oben
ln -s /dev/ttySU2 /dev/com7
# Pfostenstecker Mitte
ln -s /dev/ttySU3 /dev/com8


