#!/bin/sh
#*****************************************************************************
#* 
#*  @file          S21firstboot
#*
#*  /etc/init.d    script initializes the ssh keys on first system boot 
#*
#*  @version       1.0 (\$Revision: 1818 $)
#*  @author        Markus Forster <br>
#*                 Weiss-Electronic GmbH
#* 
#*  $LastChangedBy: fom9tr $  
#*  $Date: 2006-08-27 $
#*  $URL:  $
#*
#*  @par Modification History:
#*    2006-08-27 mf: initial version (unixdef)
#*
#*  
#*****************************************************************************

umask 022

if [ ! -f /etc/.firstboot ]; then
    exit 0
else
    /etc/ssh_keygen.sh &
fi
