#!/bin/sh
#*****************************************************************************
#* 
#*  @file          S*grps
#*
#*  Start GPRS dialin ppp network interface
#*
#*  @version       1.0 (\$Revision$)
#*  @author        Guido Classen <br>
#*                 Weiss-Electronic GmbH
#* 
#*  $LastChangedBy$  
#*  $Date$
#*  $URL$
#*
#*  @par Modification History:
#*    2007-12-03 gc: initial version
#*  
#*****************************************************************************


if ! [ -f /etc/default/gprs ]
then
# GPRS not configured -> exit
  exit 1
fi

. /etc/default/gprs

if [ -z "$GPRS_DEVICE" -o \
     -z "$GPRS_APN" ]
then
  echo "Necessary settings missing in /etc/default/gprs"
  exit 1
fi

start() {
	if [ -f /tmp/gprs_disable ]
	then
  		echo "GPRS dialin disabled"
  		exit 1
	fi

	echo "Starting GPRS PPP dialin interface"
	nohup /usr/bin/starter_gprs_dialin >/dev/null 2>&1 &
}	

stop() {
	echo "Stopping GPRS PPP dialin interface"
	killall starter_gprs_dialin
}

restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

