#!/bin/sh
#
# Start the network....
#


# internationalization function for messages (identity)
M_() {
  echo "$@"
}
if [ -x /usr/swarco/bin/sys-mesg ]; then
    SYS_MESG=/usr/swarco/bin/sys-mesg
else
    SYS_MESG=/usr/weiss/bin/sys-mesg
fi

start() {
 	echo "Starting network..."

        #check ethernet MAC address
        if ifconfig eth0 | grep -q "HWaddr 00:00:00:00:00:00" >/dev/null 2>&1; then
            $SYS_MESG -n "network" -e eth0/mac -p error `M_ "Ethernet MAC address lost. Probably EEPROM contents invalid" `
        fi

	# disable ARP replies with IP addresses of other interfaces
        echo 1 >/proc/sys/net/ipv4/conf/all/arp_ignore 

        # 2007-05-09 gc: ifup seams currently not to work in busybox
	#/sbin/ifup -a
	sh /etc/network/ip-config
}	
stop() {
	echo -n "Stopping network..."
	#/sbin/ifdown -a
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

# Local Variables:
# mode: shell-script
# backup-inhibited: t
# End:
