#!/bin/sh

NTPDATE=/usr/bin/ntpdate
HWCLOCK=/sbin/hwclock
NTPSERVERS="ptbtime1.ptb.de"

# synchronize systime from NTP-Server
test -f $NTPDATE || exit 0
#test -f /etc/default/ntp-servers || exit 0
#
#. /etc/default/ntp-servers
#
#test -n "$NTPSERVERS" || exit 0

logger "$0 Running ntpdate to synchronize clock"
$NTPDATE -t 120 $NTPSERVERS && $HWCLOCK -w
logger "$0 ntpdate finished with: `$HWCLOCK`"
