#!/bin/sh


start() {
    if test -f /etc/default/ntpdate ; then
	nohup /usr/bin/ntp-query.sh >/dev/null 2>&1 &
    fi
}

case "$1" in
    start)
	start
        ;;
    stop)
        ;;
  restart|reload)
	start	
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

