#!/bin/sh

if [ -f /etc/default/gprs ]
then

  . /etc/default/gprs
  
  if [ \! -z "$GPRS_PPP_IFACE" \
      -a "$PPP_IFACE" = "$GPRS_PPP_IFACE" ]
  then

	echo GPRS_ERROR_COUNT=0 >/tmp/gprs-error
  fi

fi
