#!/bin/sh


set_gprs_led() {
    echo 0 "$*" >/tmp/gprs_led 
}

if [ -f /etc/default/gprs ]
then

  . /etc/default/gprs
  
  if [ \! -z "$GPRS_PPP_IFACE" -a \! -z "$GPRS_PPP_LED" ]
  then

      if [ $PPP_IFACE = $GPRS_PPP_IFACE ] 
      then
          #echo 100 >$GPRS_PPP_LED
          set_gprs_led on
      fi
  fi
fi
