#!/bin/sh
#*****************************************************************************
#* 
#*  @file          /etc/S*sysv-ipc-limits
#*
#*                 Setze Linux Kernel Sys-V interprocess communication limits
#*                 2005 Weiss-Electronic GmbH
#*                 2010 SWARCO Traffic Systems GmbH
#*
#*  @version       0.3
#*  @date          <2011-01-10 19:33:25 gc>
#*  @author        Guido Classen
#* 
#*  @par change history:
#*    2005-06-07 gc: initial version 
#*  
#*****************************************************************************

case "$1" in
  start)
	# break
	;;
  stop)
  	exit 0
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac


##############################################################################
# 2005-06-08 gc: Shell functions
##############################################################################
sysctl() {
   case "$1" in
   -w)	
	assignment=$2
	echo ${assignment##*=} >/proc/sys/${assignment%%=*}
	;;
   *)
	echo $1 = `echo /proc/sys/$1`
	return 1
	;;
    esac
    return 0
}

##############################################################################
# 2005-06-08 gc: End shell functions
##############################################################################

#2003-05-16 gc:
echo "Setting SysV IPC limits"
#maximal size in bytes of all messages in queue
sysctl -w kernel/msgmnb=1048576
#maximal number of message queues in system
sysctl -w kernel/msgmni=256


# Local Variables:
# mode: shell-script
# time-stamp-pattern: "20/@date[\t ]+<%%>"
# backup-inhibited: t
# End:
