#!/bin/sh
#
# Start the network....
#

start() {
 	echo "Starting network..."
        # 2007-05-09 gc: ifup seams currently not to work in busybox
	#/sbin/ifup -a
	sh /etc/network/ip-config
}	
stop() {
	echo -n "Stopping network..."
	#/sbin/ifdown -a
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

